Vagrant.configure("2") do |config|
    config.vm.box = "tas50/macos_10.15"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
    end

    config.vm.provision "shell", inline: <<-SHELL
    curl "https://download.visualstudio.microsoft.com/download/pr/3b305e51-67fb-47cf-a916-700e62148324/1b71cd10822a3a1805008e212157a178/dotnet-sdk-6.0.416-osx-x64.pkg" \
    -o dotnet_installer.pkg
    sudo installer -pkg dotnet_installer.pkg -target /
    sudo mkdir -p -m 775 /usr/local/bin
    sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/
    dotnet tool install --tool-path /usr/local/share --version 1.0.0 --add-source http://192.168.0.103:5000/v3/index.json --no-cache ykivlyuk
    sudo ln -s /usr/local/share/ykivlyuk /usr/local/bin/
    SHELL

end