Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000
 
  config.vm.provider "virtualbox" do |vb|
  # # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  #
  # # Customize the amount of memory on the VM:
  # vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
 
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "shell", inline: <<-SHELL

    sudo apt-get update
    sudo apt-get upgrade
  
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0

    sudo apt-get install -y git

    git clone https://github.com/yura-kiv/crossplatform-uni.git

    cd crossplatform-uni/Lab5WebApp

    dotnet run

    SHELL
end